services:
  - type: web
    name: knowbie
    env: python
    plan: free

    # 1) install Python deps; 2) build your React app
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      cd react-vite
      npm ci
      npm run build

    # Run your migrations then launch with Gunicorn
    startCommand: |
      flask --app app db upgrade
      flask --app app seed all
      python -m gunicorn --bind 0.0.0.0:$PORT app:app

    envVars:
      - key: DATABASE_URL
        fromDatabase: knowbie-db
      - key: SECRET_KEY
        sync: false