services:
  - type: web
    name: knowbie
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      cd react-vite
      npm install
      npm run build

    startCommand: gunicorn app:app

    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false