"""Initial clean schema

Revision ID: 58732b5c8461
Revises: 
Create Date: 2025-06-12 13:54:04.441227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58732b5c8461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom_quizzes', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom_quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
