"""Make quiz_id nullable on Feedback

Revision ID: c07dce24ad6e
Revises: 6cd1660d45e0
Create Date: 2025-05-05 11:40:37.501537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07dce24ad6e'
down_revision = '6cd1660d45e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
